version: "3.2"
services:
  nsqd:
    image: cturley/nsqd
    command: |
      /nsqd
      --lookupd-tcp-address=nsqlookupd:4160
      --tls-root-ca-file=/etc/ssl/certs/root.crt
      --tls-cert=/etc/ssl/certs/dev.internal.crt
      --tls-key=/etc/ssl/certs/dev.internal.key
      --tls-required=true
      --data-path=/tmp/nsq
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151
      - 4152:4152
    links:
      - nsqlookupd
    volumes:
      - ./certs:/etc/ssl/certs
      - ./data:/tmp/nsq
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - 4160
      - 4161
  nsqadmin:
    image: nsqio/nsq
    command: |
      /nsqadmin
      --lookupd-http-address=nsqlookupd:4161
      --http-client-tls-insecure-skip-verify=true
    depends_on:
      - nsqlookupd
    ports:
      - 4171:4171
    links:
      - nsqlookupd

  consumer:
    build:
      context: .
    command: consumer
    links:
      - nsqd
      - nsqlookupd
  producer:
    build:
      context: .
    command: producer
    links:
      - nsqd
